services:
  dnsserver:
    build: dnsserver
    hostname: darthvader
    ports:
      - 192.168.20.10:53:53    #So na rede principal
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
    networks:
      rededns:
        ipv4_address: 192.168.20.10
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 172.25.0.100
    dns: 192.168.20.10
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24
